"""
Ecrire un programme qui demande chacune de ces informations, et les garde dans des variables 
appropriées.
"""

from datetime import date
import time
import pycountry as p
from deep_translator import GoogleTranslator

country_name = [
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Netherlands Antilles",
    "Angola",
    "Antarctica",
    "Argentina",
    "American Samoa",
    "Austria",
    "Australia",
    "Aruba",
    "Åland Islands",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Saint Barthélemy",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "British Antarctic Territory",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos [Keeling] Islands",
    "Congo - Kinshasa",
    "Central African Republic",
    "Congo - Brazzaville",
    "Switzerland",
    "Côte d’Ivoire",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Serbia and Montenegro",
    "Canton and Enderbury Islands",
    "Cuba",
    "Cape Verde",
    "Curaçao",
    "Christmas Island",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Micronesia",
    "Faroe Islands",
    "French Southern and Antarctic Territories",
    "France",
    "Metropolitan France",
    "Gabon",
    "United Kingdom",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia and the South Sandwich Islands",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong Kong SAR China",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Johnston Island",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "Saint Kitts and Nevis",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Marshall Islands",
    "Midway Islands",
    "Macedonia",
    "Mali",
    "Myanmar [Burma]",
    "Mongolia",
    "Macau SAR China",
    "Northern Mariana Islands",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Dronning Maud Land",
    "Nauru",
    "Neutral Zone",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Pacific Islands Trust Territory",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Pitcairn Islands",
    "Puerto Rico",
    "Palestinian Territories",
    "Portugal",
    "U.S. Miscellaneous Pacific Islands",
    "Palau",
    "Paraguay",
    "Panama Canal Zone",
    "Qatar",
    "Réunion",
    "Romania",
    "Serbia",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena",
    "Slovenia",
    "Svalbard and Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "São Tomé and Príncipe",
    "Union of Soviet Socialist Republics",
    "El Salvador",
    "Syria",
    "Swaziland",
    "Turks and Caicos Islands",
    "Chad",
    "French Southern Territories",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "Timor-Leste",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "U.S. Minor Outlying Islands",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vatican City",
    "Saint Vincent and the Grenadines",
    "North Vietnam",
    "Venezuela",
    "British Virgin Islands",
    "U.S. Virgin Islands",
    "Vietnam",
    "Vanuatu",
    "Wallis and Futuna",
    "Wake Island",
    "Samoa",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe",
]

nationality = [
    "Andorran",
    "Emirati",
    "Afghan",
    "Antiguan, Barbudan",
    "Anguillian",
    "Albanian",
    "Armenian",
    "Dutch",
    "Angolan",
    "???",
    "Argentinean",
    "American Samoan",
    "Austrian",
    "Australian",
    "Aruban",
    "Swedish",
    "Azerbaijani",
    "Bosnian, Herzegovinian",
    "Barbadian",
    "Bangladeshi",
    "Belgian",
    "Burkinabe",
    "Bulgarian",
    "Bahraini",
    "Burundian",
    "Beninese",
    "Saint Barthélemy Islander",
    "Bermudian",
    "Bruneian",
    "Bolivian",
    "Dutch",
    "Brazilian",
    "Bahamian",
    "Bhutanese",
    "???",
    "Motswana",
    "Belarusian",
    "Belizean",
    "Canadian",
    "Cocos Islander",
    "Congolese",
    "Central African",
    "Congolese",
    "Swiss",
    "Ivorian",
    "Cook Islander",
    "Chilean",
    "Cameroonian",
    "Chinese",
    "Colombian",
    "Costa Rican",
    "Montenegrins, Serbs",
    "???",
    "Cuban",
    "Cape Verdian",
    "Curaçaoan",
    "Christmas Island",
    "Cypriot",
    "Czech",
    "German",
    "Djibouti",
    "Danish",
    "Dominican",
    "Dominican",
    "Algerian",
    "Ecuadorean",
    "Estonian",
    "Egyptian",
    "Sahrawi",
    "Eritrean",
    "Spanish",
    "Ethiopian",
    "Finnish",
    "Fijian",
    "Falkland Islander",
    "Micronesian",
    "Faroese",
    "???",
    "French",
    "???",
    "Gabonese",
    "British",
    "Grenadian",
    "Georgian",
    "???",
    "Channel Islander",
    "Ghanaian",
    "Gibraltar",
    "Greenlandic",
    "Gambian",
    "Guinean",
    "Guadeloupian",
    "Equatorial Guinean",
    "Greek",
    "South Georgia and the South Sandwich Islander",
    "Guatemalan",
    "Guamanian",
    "Guinea-Bissauan",
    "Guyanese",
    "Chinese",
    "Heard and McDonald Islander",
    "Honduran",
    "Croatian",
    "Haitian",
    "Hungarian",
    "Indonesian",
    "Irish",
    "Israeli",
    "Manx",
    "Indian",
    "Indian",
    "Iraqi",
    "Iranian",
    "Icelander",
    "Italian",
    "Channel Islander",
    "Jamaican",
    "Jordanian",
    "Japanese",
    "???",
    "Kenyan",
    "Kirghiz",
    "Cambodian",
    "I-Kiribati",
    "Comoran",
    "Kittian and Nevisian",
    "North Korean",
    "South Korean",
    "Kuwaiti",
    "Caymanian",
    "Kazakhstani",
    "Laotian",
    "Lebanese",
    "Saint Lucian",
    "Liechtensteiner",
    "Sri Lankan",
    "Liberian",
    "Mosotho",
    "Lithuanian",
    "Luxembourger",
    "Latvian",
    "Libyan",
    "Moroccan",
    "Monegasque",
    "Moldovan",
    "Montenegrin",
    "Saint Martin Islander",
    "Malagasy",
    "Marshallese",
    "???",
    "Macedonian",
    "Malian",
    "Myanmar",
    "Mongolian",
    "Chinese",
    "American",
    "French",
    "Mauritanian",
    "Montserratian",
    "Maltese",
    "Mauritian",
    "Maldivan",
    "Malawian",
    "Mexican",
    "Malaysian",
    "Mozambican",
    "Namibian",
    "New Caledonian",
    "Nigerian",
    "Norfolk Islander",
    "Nigerian",
    "Nicaraguan",
    "Dutch",
    "Norwegian",
    "Nepalese",
    "???",
    "Nauruan",
    "???",
    "Niuean",
    "New Zealander",
    "Omani",
    "Panamanian",
    "???",
    "Peruvian",
    "French Polynesian",
    "Papua New Guinean",
    "Filipino",
    "Pakistani",
    "Polish",
    "French",
    "Pitcairn Islander",
    "Puerto Rican",
    "Palestinian",
    "Portuguese",
    "???",
    "Palauan",
    "Paraguayan",
    "???",
    "Qatari",
    "French",
    "Romanian",
    "Serbian",
    "Russian",
    "Rwandan",
    "Saudi Arabian",
    "Solomon Islander",
    "Seychellois",
    "Sudanese",
    "Swedish",
    "Singaporean",
    "Saint Helenian",
    "Slovene",
    "Norwegian",
    "Slovak",
    "Sierra Leonean",
    "Sammarinese",
    "Senegalese",
    "Somali",
    "Surinamer",
    "Sao Tomean",
    "???",
    "Salvadoran",
    "Syrian",
    "Swazi",
    "Turks and Caicos Islander",
    "Chadian",
    "French",
    "Togolese",
    "Thai",
    "Tadzhik",
    "Tokelauan",
    "East Timorese",
    "Turkmen",
    "Tunisian",
    "Tongan",
    "Turkish",
    "Trinidadian",
    "Tuvaluan",
    "Taiwanese",
    "Tanzanian",
    "Ukrainian",
    "Ugandan",
    "American",
    "American",
    "Uruguayan",
    "Uzbekistani",
    "Italian",
    "Saint Vincentian",
    "???",
    "Venezuelan",
    "Virgin Islander",
    "Virgin Islander",
    "Vietnamese",
    "Ni-Vanuatu",
    "Wallis and Futuna Islander",
    "???",
    "Samoan",
    "Yemeni",
    "French",
    "South African",
    "Zambian",
    "Zimbabwean",
]

nn_mapping = dict(zip(country_name, nationality))

t = GoogleTranslator(source="auto", target="fr")


def identite():
    "..."
    nom = str(input("Nom : "))
    prenom = str(input("Prenom : "))
    while not nom.isalpha() or not prenom.isalpha():
        print("Nom ou Prenom Invalide! Veuillez essayer une autre entree.")
        nom = str(input("Nom : "))
        prenom = str(input("Prenom : "))
    # Date de Naissance
    jour, mois, annee = (input("Date de naissance (Format JJ-MM-AAAA) : ")).split("-")
    date_de_naissance = date(int(annee), int(mois), int(jour))
    mois_de_lannee = {
        1: "Janvier",
        2: "Fevrier",
        3: "Mars",
        4: "Avril",
        5: "Mai",
        6: "Juin",
        7: "Juillet",
        8: "Aout",
        9: "Septembre",
        10: "Octobre",
        11: "Novembre",
        12: "Decembre",
    }
    mois = mois_de_lannee[int(mois)]
    delta = date.today() - date_de_naissance
    age = int(delta.days / 365.25)
    if age >= 18:
        legalite = "Majeur"
    else:
        legalite = "Mineur"
    # Sexe et titre
    sexe = str(input("Sexe (M: Masculin/F: Feminin/N: Non identifie): "))
    while sexe.capitalize() not in ("M", "F", "N"):
        print("Mauvaise entree!")
        sexe = str(input("Sexe (M: Masculin/F: Feminin/N: Non identifie): "))
    if sexe == "M":
        civilite = "Mr."
    elif sexe == "F":
        civilite = "Mme."
    else:
        civilite = "Mr./Mme"
    pays_de_naissance = str(input("Pays de naissance : "))
    while p.countries.get(name=pays_de_naissance.title()) is None:
        print("Pays de Naissance Invalide! Essayez une autre entree.")
        pays_de_naissance = str(input("Pays de naissance : "))
    adresse = str(input("Votre adresse actuelle : "))
    nationalite = t.translate(text=nn_mapping[pays_de_naissance])

    time.sleep(2)
    print("\n\nVeuillez patienter...")
    time.sleep(4)

    print(
        f"""\n\n\n
    Recapitulatif de l'identite de {civilite} {nom}.
        Nom          :   {nom}
        Prenom       :   {prenom}
        Sexe         :   {sexe}
        Date de Naissance: {jour} {mois} {annee}
        Age          :   {age}
        Legalite     :   {legalite}
        Adresse      :   {adresse}
        Nationalite  :   {nationalite.title()}
    """
    )
    time.sleep(2)


if __name__ == "__main__":
    identite()
